### ISSUE TITLE
PHP Fatal error:  Trait 'yiicod\jobqueue\commands\WorkerTrait' not found

### ISSUE THREAD

**Issue by jjmaceda** [yiicod/yii2-jobqueue#1]
Hi, I'm getting this error when I try to start the queue daemon, any ideas? thanks!

**Comment by lexxorlov** [comment]
I have fixed the problem. But this more preferable variant https://github.com/yiicod/yii2-jobqueue#console-config--pm2httppm2keymetricsio-this-variant-more-preferable-for-console-configuration
